### ISSUE TITLE
Will FreeType be supported ? 

### ISSUE THREAD

**Issue by blackball** [swistakm/pyimgui#107]
Hi, 

I would like to make my font looks better. One way as the imgui C++ does, is to make use of freetype lib. I wonder when will pyimgui support this functionality, also for now, what is the suggested way to achieve the same goal. 

Thanks!

**Comment by swistakm** [comment]
This is definitely possible right now. I have tested that already with TTF fonts and documentation of core ImGui lib suggests it should work with OpenType fonts too. I will test it myself and provide some examples & documentation on the readthedocs to show how to do this.

**Comment by blackball** [comment]
I am using freetype to get a good looking for the fonts.
