### ISSUE TITLE
CalcTextSize() not mapped

### ISSUE THREAD

**Issue by n00bmind** [swistakm/pyimgui#117]
Hi,
Wanted to thank you guys for the possibility of using ImGui awesomeness from python.. talk about RAD! x)

I'm currently looking for a way to right align some text (numeric quantities) to make it more readable. I believe the usual approach in the original api is to just find out the size of the text to print and manually move the cursor to the right of the window minus the text width.
However I cannot find a way to do this currently in python since the useful CalcTextSize() function is not mapped.
Any chance of getting this soon?

Thanks!

**Comment by swistakm** [comment]
Sorry, we still haven't ported that yet. I'll add this to the next milestone.

**Comment by n00bmind** [comment]
Cool thanks!

**Comment by dee909** [comment]
+1 for CalcTextSize(), layouting without it is really difficult :'(

**Comment by TTimo** [comment]
+1

**Comment by KinoxKlark** [comment]
``CalcTextSize()`` has been mapped in #191 :)

**Comment by dee909** [comment]
Awesome ! <3

**Comment by swistakm** [comment]
Released as `1.3.0`:
- [release notes](https://github.com/swistakm/pyimgui/releases/tag/1.3.0)
- [available distributions](https://pypi.org/project/imgui/1.3.0/#files)
