### ISSUE TITLE
Window resizing does not work properly with the pygame backend

### ISSUE THREAD

**Issue by RosenGeorgiev** [swistakm/pyimgui#128]
When attempting to resize a window, it resizes, but it's contents stay the same size, drift outside the visible area and I get some black margins around it. Also the mouse is kind of offset. Does anyone know a fix/workaround for this?

![shot](https://user-images.githubusercontent.com/17404122/64648718-2e2b1f80-d424-11e9-8dfe-faea8cae0440.png)

I'm using the code from <code>examples/integrations_pygame.py</code>, but I have added <code>pygame.RESIZABLE</code> to the <code>pygame.display.set_mode</code> call. Also ImGui's <code>io.display_size</code> seems to be getting updated from the resize events, so I guess that's not the cause of the problem.

**Comment by swistakm** [comment]
Found the issue and fixed it. Resizing in pygame is a bit wonky but should work now.

I will remove "release pending" label when it's finally on PyPI

**Comment by swistakm** [comment]
This has been released in [1.1.0](https://github.com/swistakm/pyimgui/releases/tag/1.1.0) and is available for download from PyPI.
