### ISSUE TITLE
ModuleNotFoundError when trying to run example code for Pyglet on Python 3.8

### ISSUE THREAD

**Issue by jaapiyo** [swistakm/pyimgui#132]
When I try to run the example code for the Pyglet implementation I get the following error:
```
PS "C:/Program Files (x86)/Python38-32/python.exe" "f:/Jaap/imgui.py"
  File "f:/Jaap/imgui.py", line 7, in <module>
    import imgui
  File "f:\imgui.py", line 8, in <module>
    from imgui.integrations.pyglet import PygletRenderer
ModuleNotFoundError: No module named 'imgui.integrations'; 'imgui' is not a package
```
I have installed Pyimgui using Pip and that went without problems so I'm not shure where to search next.

**Comment by einarf** [comment]
Having this problem for py38 in general across all platforms. I guess a new release with 3.8 wheels needs to be released to solve this.

**Comment by jaapiyo** [comment]
Thanks for your reply, but downgrading to Python 3.6 doesn't seem to fix the issue.

**Comment by einarf** [comment]
`from imgui.integrations.pyglet import PygletRenderer` works fine for me in win10 with python 3.7 64 bit.

**Comment by swistakm** [comment]
@einarf you're right, the wheel for Python3.8 is not published yet. I will add it to the build matrix in incoming release.

@jaapiyo do you get exactly the same error on Python3.6? It should already work well on both Python3.6 and Python3.7. What do you get if you run following:
```
import imgui
print(imgui)
```

**Comment by jaapiyo** [comment]
I found the problem! I named my test file `imgui.py`. After renaming it to `imguitest.py` it worked like a charm. Thank you for your help!
