### ISSUE TITLE
got nothing with "Basic GUI drawing loop"

### ISSUE THREAD

**Issue by kaixin-bai** [swistakm/pyimgui#153]
after install pyimgui with ``pip install imgui[full]``, i tried "Basic GUI drawing loop" in [First steps with imgui](https://pyimgui.readthedocs.io/en/latest/guide/first-steps.html) and nothing showed.

**Comment by swistakm** [comment]
Hi, I understand that current documentation isn't explicit enough about that but you need to select specific rendering backend (e.g. glfw, pyglet, cocos2d) and use one of provided integration packages. It was already briefly discussed in https://github.com/swistakm/pyimgui/issues/46#issuecomment-325189992

> Everything is explained in the documentation page titled First steps with imgui. Links to the examples can be found on the bottom of that page. They lead directly to doc/examples project source tree on GitHub.
> Read it carefully and you should be able to make your own GUI in a few minutes.

**Comment by kaixin-bai** [comment]
Thanks for reply!
