### ISSUE TITLE
`get_column_width()` returns None

### ISSUE THREAD

**Issue by dee909** [swistakm/pyimgui#179]
We can deal with `get_column_offset()` but it would be nice(r) to use width directly.

**Comment by swistakm** [comment]
Fixed by #175. Release pending, stay tuned.

**Comment by swistakm** [comment]
Released as `1.3.0`:
- [release notes](https://github.com/swistakm/pyimgui/releases/tag/1.3.0)
- [available distributions](https://pypi.org/project/imgui/1.3.0/#files)
