### ISSUE TITLE
input_double() actually calls InputInt()

### ISSUE THREAD

**Issue by connorjak** [swistakm/pyimgui#185]
https://github.com/swistakm/pyimgui/blob/4eb8a65a7f345fb447ba7d6902be86ecb5413e1e/imgui/core.pyx#L5364

This results in an input_double that behaves exactly like input_int.

**Comment by swistakm** [comment]
I'm closing this as we already have MR for that #193 which requires only minor improvement.

**Comment by swistakm** [comment]
Released as `1.3.0`:
- [release notes](https://github.com/swistakm/pyimgui/releases/tag/1.3.0)
- [available distributions](https://pypi.org/project/imgui/1.3.0/#files)
