### ISSUE TITLE
cannot import imgui from embedded python (windows)

### ISSUE THREAD

**Issue by pbuckner** [swistakm/pyimgui#220]
I have embedded python as a plugin in a C++ executable. From python, I can execute any python code, import modules, etc.

When attempting to import imgui, I get a windows 10 (with python3.9) error:

```
File ..\imgui\__init.py, line 8, in <module>
  from .core import *
ImportError: DLL load failed while importing core: The parameter is incorrect.
```

Import works fine with Mac (Big Sur & python3.9). I've not tested with Linux.

*.pyd files are DLLs, but slightly different. The reference error, I think, has to do with windows activation context (which is a mystery to me). I suspect part of the problem is the *.pyd thinks it is `image.core`, but the windows DLL loader needs `core`.

Compare with, for example, the standard socket lib, where `socket.py` simply calls `import _socket; from _socket import *`, where "_socket" is not a sub-module. The shared pyd `_socket.*.pyd` lives with other DLLs (though it should be able to live anywhere on PYTHONPATH). Notable, it does NOT exist as a submodule.

What would it take to convert the existing `core.*.pyd`, `core.*.so` to simply `_imgui`...? and modify `imgui/__init__.py` to import _imgui directly from the DLL/SO?

**Comment by learn-more** [comment]
> I have embedded python as a plugin in a C++ executable. From python, I can execute any python code, import modules, etc.
> 
> When attempting to import imgui, I get a windows 10 (with python3.9) error:
> 
> ```
> File ..\imgui\__init.py, line 8, in <module>
>   from .core import *
> ImportError: DLL load failed while importing core: The parameter is incorrect.
> ```
> 
> Import works fine with Mac (Big Sur & python3.9). I've not tested with Linux.
> 
> *.pyd files are DLLs, but slightly different. The reference error, I think, has to do with windows activation context (which is a mystery to me). I suspect part of the problem is the *.pyd thinks it is `image.core`, but the windows DLL loader needs `core`.
> 
> Compare with, for example, the standard socket lib, where `socket.py` simply calls `import _socket; from _socket import *`, where "_socket" is not a sub-module. The shared pyd `_socket.*.pyd` lives with other DLLs (though it should be able to live anywhere on PYTHONPATH). Notable, it does NOT exist as a submodule.
> 
> What would it take to convert the existing `core.*.pyd`, `core.*.so` to simply `_imgui`...? and modify `imgui/__init__.py` to import _imgui directly from the DLL/SO?

Some things to check:
* Is you windows executable the same architecture as the *.pyd file (32 vs 64 bits)?
* When looking at a random python 37 installation, I do not see a special manifest file, which would suggest that python does not require a special activation context.
  * If you still suspect it is an SxS issue, this guide explains fairly well how to debug it: http://ntcoder.com/bab/2014/02/27/troubleshooting-side-by-side-issues-using-sxstrace/
* If you have the debugging tools for windows, start a tool called `gflags.exe` from that. Otherwise grab GflagsX from https://github.com/zodiacon/GflagsX
 * navigate to the 'Image file' tab
 * type your process name in that box (including extension)
 * Tick the box 'Show loader snaps'
 * Run your application under a debugger, it should now show all dll's that it is trying to load

**Comment by pbuckner** [comment]
Continuing to investigate. 

I can get it to work if I place core...pyd into `c:\Program Files\Python39\DLLs` folder **and** change its import in `imgui/__init__.py` to simply `import core`. (Again, it might be better long-term issue to use `_imgui` rather than `core`.)

I'll report back on gflagx debugging. Using procmon I was able to see some PYDs load, most from Python39/DLLs, but one from under site-packages. Need to investigate how the one under site-packages worked, as that's more likely the pattern most likely to succeed for simpler user installation.

**Comment by learn-more** [comment]
https://blog.pyspoken.com/2016/04/27/embedding-python-how-to-confuse-python-and-yourself/ explains some common pitfalls

**Comment by pbuckner** [comment]
Update: I've been building windows version with mingw toolchain. -- I think that's source of the problem.

With mingw version, resulting pyd can be loaded directly using pythonw.exe or IDLE. But I get the error only when attempting to load in embedded app.

python docs https://docs.python.org/3/faq/windows.html mention:

> There are two problems with Pythons C API which will become apparent if you use a compiler other than MSVC, the compilter used to build pythonNN.dll
>
> Problem 1: The so-called "Very High Level" functions that take FILE * arguments will not work in multi-compiler environment because each compiler's notion of a struct FILE will be different. From and implementation standpoint these are very _low_ level functions.

(I've not noticed other issues with mingw vs msvc, but perhaps I've not needed to pass a FILE structure from one compiler's code to another compiler's code?)

So, I'm trying to rebuild with MSVC tool chain to see if that makes a difference for embedded.

**Comment by learn-more** [comment]
> Update: I've been building windows version with mingw toolchain. -- I think that's source of the problem.
> 
> With mingw version, resulting pyd can be loaded directly using pythonw.exe or IDLE. But I get the error only when attempting to load in embedded app.
> 
> python docs https://docs.python.org/3/faq/windows.html mention:
> 
> > There are two problems with Pythons C API which will become apparent if you use a compiler other than MSVC, the compilter used to build pythonNN.dll
> > Problem 1: The so-called "Very High Level" functions that take FILE * arguments will not work in multi-compiler environment because each compiler's notion of a struct FILE will be different. From and implementation standpoint these are very _low_ level functions.
> 
> (I've not noticed other issues with mingw vs msvc, but perhaps I've not needed to pass a FILE structure from one compiler's code to another compiler's code?)
> 
> So, I'm trying to rebuild with MSVC tool chain to see if that makes a difference for embedded.

Yes, that seems like it would cause a lot of problems.
One possible other solution for this would be to not use an embedded c runtime, but use the OS's version.
However, using the same compiler on both is safer.

**Comment by pbuckner** [comment]
having problems building from command line (powershell) with msvc. I can run

py -m pip install -e . -v

directly, skipping makefile & it compiles correctly, but resulting final link misses pulling in python.dll (python.lib?) so virtually all python symbols are undefined.

Have you been able to build on windows?

**Comment by learn-more** [comment]
I have used `py setup.py build_ext --inplace` to build it,
however it does not properly rebuild on changes to source files, so you need to delete some output files for it to trigger a re-build

**Comment by pbuckner** [comment]
> I have used py setup.py build_ext --inplace to build it,
> 
Windows weirdness.
Finally got it to compile for all 3.6-3.9 without link errors. For some reason, it was compiling 3.6 & 3.7 (successfully) using 64bit compiler, but insisted on using 32-bit for 3.8 & 3.9 which resulted in link errors.

In powershell:

c:\Program Files\Python36\python.exe setup.py build_ext --inplace
c:\Program Files\Python37\python.exe setup.py build_ext --inplace
c:\Program Files\Python38\python.exe setup.py build_ext --inplace
c:\Program Files\Python39\python.exe setup.py build_ext --inplace

I’ll test the results tomorrow (though I fear I might need to recompile my C++ plugin to use the VS compiler instead of mingw)

**Comment by pbuckner** [comment]
arrrg. Updated pyd still doesn't work & I still get "The parameter is incorrect".

Trying to port my C plugin, which embeds python to compile with Visual Studio C++ looks to be a nightmare.

As before, it works if and only if I copy the pyd to \ProgramFiles\Python39\DLLs (which required admin access). I can see the file is found each time, but it only successfully loads if it's under DLLs. Sound more like a permission problem than a compilation problem.

**Comment by learn-more** [comment]
I have created an example project that might give you a few ideas where to look:
https://github.com/learn-more/EmbedPython39

Works for me (tm) in both `Debug` and `Release`.
In the comments I have described how I obtained files / configured stuff.

**Comment by pbuckner** [comment]
Oh man... now it's working. I need to unravel the changes to see exactly what changed.

First, thanks for the example -- I was able to modify it to make it more like what I'm doing & test multiple different scenarios.

I *think* the only real change I made to my C code is using absolute paths in sys.path rather than relative paths: It appears relative paths allowed to pyd to be found, but not loaded. Changing the few relative paths to absolute paths allowed the pyd to be found and loaded. (That is, I'm still using mingw toolchain, without using addDllDirectory!)

So, put this issue on hold -- I'll do some more retesting to make sure it's a clean environment and will report back.

**Comment by pbuckner** [comment]
Solved. Indeed, it is a relative vs absolute path. You can easily test it by modifying your example.
Add 'foobar' (a relative path) to sys.path

You'll be able to `import zippy`, being foobar/zippy.y
You'll not be able to `import _zoneinfo`, if you MOVE _zoneinfo.pyd from PythonXX/DLLs to foobar. You get "The parameter is incorrect." (That is, it finds the pyd, but cannot load it).

But, if you change sys_path to add C:\TEST\foobar, you'll be able to find and load it.

So, no changed required to imgui

**Comment by learn-more** [comment]
> Solved. Indeed, it is a relative vs absolute path. You can easily test it by modifying your example.
> Add 'foobar' (a relative path) to sys.path
> 
> You'll be able to `import zippy`, being foobar/zippy.y
> You'll not be able to `import _zoneinfo`, if you MOVE _zoneinfo.pyd from PythonXX/DLLs to foobar. You get "The parameter is incorrect." (That is, it finds the pyd, but cannot load it).
> 
> But, if you change sys_path to add C:\TEST\foobar, you'll be able to find and load it.
> 
> So, no changed required to imgui

The reason why this fails is:
Python is trying to call LoadLibraryExW like this:
```
hDLL = LoadLibraryExW(wpathname, NULL,
                      LOAD_LIBRARY_SEARCH_DEFAULT_DIRS |
                      LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR);
```
with `wpathname = "lib.win-amd64-3.9\imgui\core_d.cp39-win_amd64.pyd"`,
most likely because it cannot find the pyd on it's own.
if the path is a full path, LoadLibraryExW will be called like this:
`wpathname = "E:/Projects/EmbedPython39/\lib.win-amd64-3.9\imgui\core_d.cp39-win_amd64.pyd"`
where `"E:/Projects/EmbedPython39/\lib.win-amd64-3.9"` is the path configured.
So clearly, if there are full paths in there, python is able to find the module on it's own without the help of the OS.
