### ISSUE TITLE
Running Error at basic rendering loop

### ISSUE THREAD

**Issue by EMGPY** [swistakm/pyimgui#46]
When i try to run, i am getting this error, using the basic example of readthedocs
```
Traceback (most recent call last):
  File "F:/Programming Projects/Python/twilio-app/main.py", line 3, in <module>
    imgui.new_frame()
  File "imgui\core.pyx", line 993, in imgui.core.new_frame
imgui.core.ImGuiError: ImGui assertion error (g.IO.DisplaySize.x >= 0.0f && g.IO.DisplaySize.y >= 0.0f) at imgui-cpp/imgui.cpp:2046
Process finished with exit code 1
```

Downloaded and installed trough pip install imgui[full].
PyCharm Community edition even trough python cmd i get the same error
Windows 7 SP1 x64
Python 3.6.2 virtualenv

**Comment by swistakm** [comment]
Hi @EMGPY, could you share a snippet of your code? The issue tittle says it happens at basic rendering loop, so I guess it is short and you can paste whole your code.

Have you tried using any any of the built-in integrations from `imgui.integrations` subpackage?  It seems that you don't use any these.

The error information says that internal ImGui state object isn't properly initialized yet. In such case you need to do proper initialization all by yourself. Unfortunately I didn't have enough time to document how to deal with that yet. The integration modules in `imgui.integrations` and examples under `doc/examples` may serve as a basis for making your own integrations.

**Comment by EMGPY** [comment]
```
import imgui

imgui.new_frame()
imgui.begin("Mi primera ventana", True)
imgui.text("Hola Mundo")
imgui.end()
imgui.render()
```

This is the example code i tried to run. 
About imgui.integrations i didn't used any, because don't want to used, just want to use imgui to create some basics gui apps. 
Where i can find the _doc/examples_ because in the imgui folder is missing.

**Comment by swistakm** [comment]
Oh, I see.

This won't work. `imgui` package is not able to render anything on it's own. This is why you need to either use built-in integrations or create own rendering code. Everything is explained in the documentation page titled [First steps with imgui](https://pyimgui.readthedocs.io/en/latest/guide/first-steps.html). Links to the examples can be found on the bottom of that page. They lead directly to [doc/examples](https://github.com/swistakm/pyimgui/tree/master/doc/examples) project source tree on GitHub.

Read it carefully and you should be able to make your own GUI in a few minutes.

I understand that current documentation may not be clear enough on this topic. Of course, any suggestions on improvements in this area would be very welcome.

**Comment by EMGPY** [comment]
Thanks to make it clear.
