### ISSUE TITLE
image_button not working

### ISSUE THREAD

**Issue by Gotos** [swistakm/pyimgui#47]
Hi there!

I can't get the image_button to return true. If I change my code to use a "normal" button, everything works fine, but the image_button seems to be broken in pyimgui.

```
if (imgui.image_button(texture, width, height)):
        # shows the image, but never prints "Yay"
        print("Yay")

...

if (imgui.button("test")):
        # Obviously no image, but prints "Yay" when clicked
        print("Yay")
```

I don't think I'm doing something wrong. Can you confirm this issue?

**Comment by swistakm** [comment]
Hi, I have tested it in my environment and it works fine:
![pyimgui-isse](https://user-images.githubusercontent.com/1258054/31083700-aacc62c6-a792-11e7-9d91-b72f96d479a2.gif)


Can you tell me what OS are you running and what is your rendering backend? If you're running windows it may be possible that this is some kind of output buffering problem. Have you tried doing something different than printing inside of your `if imgui.image_button(...):`? Maybe try using `exit()` or raising and exception?

**Comment by swistakm** [comment]
Also the information about your Python version and list of versions of additional Python libraries may be useful here.

**Comment by Gotos** [comment]
Interesting. I just checked it again and it works on this system just fine as well. On my other system it still doesn't work.
Both systems run Gentoo Linux, the backend used is pygame.
My desktop runs python 3.4.6, my notebook runs 3.6.1. The notebook is the one, were the image_button does not work. I just downgraded to 3.4.6 again, but that did not fix the problem.
Both systems use virtualenv with exactly the same libraries installed, according to pip list. I don't really know what could possibly make this difference...

**Comment by Gotos** [comment]
Interesting. I just checked it again and it works on this system just fine as well. On my other system it still doesn't work.
Both systems run Gentoo Linux, the backend used is pygame.
My desktop runs python 3.4.6, my notebook runs 3.6.1. The notebook is the one, were the image_button does not work. I just downgraded to 3.4.6 again, but that did not fix the problem.
Both systems use virtualenv with exactly the same libraries installed, according to pip list. I don't really know what could possibly make this difference...

By the way, the actual code I try to run is more complicated than the print, I just tried to find a minimal example.

**Comment by swistakm** [comment]
@Gotos thanks for all the info. It sounds weird indeed. I will try to run my snippet in different environments to see if I can reproduce it. It would be great if you could create a minimal script that reproduces the issue in one of your environment so I could try to run it in different vagrant boxes to see if it is system-specific problem.

Also I found one thing in core ImGui code that may result in such behavior. ImgGui uses a texture_id value (a `void *` pointer) as a widget id. By default this leads to assumption that every separate image button should have different texture id pointer, i.e. if two buttons have the same textures then they are treated as the same unique widget. Are you maybe using the same textures for multiple buttons?

If this is the case, we will have to add either add the option to use push/pop methods for id scopes or change the was how texture pointers are handled on pyimgui side.

**Comment by Gotos** [comment]
Hi o/
Here's the minimal script. I can't currently confirm that it runs with my over system cause I'm not currently at home, but on my laptop this does show the button but the print is not executed.

```#!/usr/bin/env python
from __future__ import absolute_import

import sys

import pygame
from OpenGL.GL import *

from imgui.integrations.pygame import PygameRenderer
import imgui

def loadImage(image):
    textureSurface = pygame.transform.flip(image, False, True)

    textureData = pygame.image.tostring(textureSurface, "RGBA", 1)

    width = textureSurface.get_width()
    height = textureSurface.get_height()

    texture = glGenTextures(1)
    glBindTexture(GL_TEXTURE_2D, texture)
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR)
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR)
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, width, height, 0, GL_RGBA,
                 GL_UNSIGNED_BYTE, textureData)

    return texture, width, height



def main():
    pygame.init()

    size = 800, 600

    pygame.display.set_mode(size, pygame.DOUBLEBUF | pygame.OPENGL)

    io = imgui.get_io()
    io.fonts.add_font_default()
    io.display_size = size

    renderer = PygameRenderer()

    while 1:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                sys.exit()

            renderer.process_event(event)

        imgui.new_frame()

        texture, width, height = loadImage(pygame.image.load("test.png"))

        imgui.begin("Custom window", True)
        if imgui.image_button(texture, width, height):
            print("Yay")
        imgui.end()

        # note: cannot use screen.fill((1, 1, 1)) because pygame's screen
        #       does not support fill() on OpenGL sufraces
        glClearColor(1, 1, 1, 1)
        glClear(GL_COLOR_BUFFER_BIT)
        imgui.render()

        pygame.display.flip()

if __name__ == "__main__":
    main()```

**Comment by swistakm** [comment]
I tried your script and successfully reproduced your issue. Still, I don't know if this is the same problem you're experiencing.

You run following line on every frame:

    texture, width, height = loadImage(pygame.image.load("test.png")) 

It loads 'test.png' and creates new texture file. The `texture` variable will have different value every time you execute `imgui.image_button` function. Usually ImGui tracks widgets by their names or other unique value (e.g. text in the text label) to guess if given user interaction between subsequent frames refers to the same widget. Image buttons don't have names or labels so the texture value is used as a identifier for that widget. It means that on every frame your image button will be treated as completely different widget. It may visually look like button is clicked but actual clicking for a button never resolves and  and this is why you don't get proper return value.

Try moving the `loadImage(pygame.image.load("test.png"))` call outside of the `while` loop and store texture in one variable that will not change it's value between frames.

**Comment by swistakm** [comment]
OK, I assume this is fixed.

**Comment by Gotos** [comment]
Sorry that I never responded to your last message. Your explanation made sense at the time, but if I recall correctly I decided not to use an image button for my problem in the end and didn't get around to try and fix my old code with your input.
Thanks for your time!

**Comment by swistakm** [comment]
No problem. I'm just doing a cleanup :)
