### ISSUE TITLE
Loading TTF fonts

### ISSUE THREAD

**Issue by iliyang** [swistakm/pyimgui#50]
I just tried to figure on my own how to load TTF fonts (documentation pending in #34), but I get an assertion error. What I do is the following:

```python
font = imgui.get_io().fonts.add_font_from_file_ttf("fonts/DroidSans.ttf", 16)
...
while not glfw.window_should_close(self.window):
    # draw stuff
    imgui.push_font(font)
    # draw text
    imgui.pop_font()
```
The font seems to load successfully, i.e. the `font` variable is a valid object, not `None`. But then I get an error upon calling `push_font`:
```
Traceback (most recent call last):
  File "/Users/...[location].../igui.py", line 200, in <module>
    app.main_loop()
  File "/Users/...[location].../igui.py", line 76, in main_loop
    self.draw()
  File "/Users/...[location].../igui.py", line 86, in draw
    self.draw_contents()
  File "/Users...[location].../igui.py", line 152, in draw_contents
    imgui.push_font(font)
  File "imgui/core.pyx", line 4757, in imgui.core.push_font
imgui.core.ImGuiError: ImGui assertion error (font && font->IsLoaded()) at imgui-cpp/imgui.cpp:4529
```

Commenting out the `push_font` and `pop_font` calls makes everything work, but with the default raster font (which doesn't look great on a high-resolution display).

I also tried displaying the font atlas on screen -- the loaded font doesn't show in the atlas, only the default raster font 

Any ideas will be greatly appreciated! I'm running macOS 10.12, tried the above code with both Python 2.7 and 3.6, both fail the same way.

**Comment by swistakm** [comment]
I could reproduce it and know the reason. 

The `io.fonts.add_font_from_file_ttf` loads the font but does not create any texture. All rendering is left for specific implementations so imgui doesn't even know how to create textures.

If you use any of the provided rendered implementations, you should either create all fonts before you create renderer or simply revalidate the font textures using `refresh_font_texture()`. For instance:

    impl = GlfwRenderer(window)
    # ....
    font_extra = io.fonts.add_font_from_file_ttf(
        "CODE2000.TTF", 30, io.fonts.get_glyph_ranges_latin()
    )
    impl.refresh_font_texture()
    # ...

    while not glfw.window_should_close(self.window):
        # draw stuff
        imgui.push_font(font)
        # draw text
        imgui.pop_font()

I know this is not intuitive. I will try to improve documentation in future so this will be more clear.

**Comment by iliyang** [comment]
Ooh, so I was only missing the call `impl.refresh_font_texture()`. Adding it works and I can now use custom fonts. Brilliant, thank you so much for your help @swistakm!

**Comment by iliyang** [comment]
One more detail, for those working on high-resolution displays with scaling enabled (e.g. Mac retina displays). Fonts will appear blurry unless you scale them manually. The default font will always appear blurry because it's pre-baked and I don't know if that can be changed. So on such a display you'll always want to use a custom font. Here's how it works in **pyimgui**.

Say you want a font size of 14. For a Mac retina display, you should load your font with 2x larger size, so that it's rasterized into the font atlas texture large, and then scale it back down for the actual display. Here's example code:

```python
impl = GlfwRenderer(window)
# ....
font_size = 14
font_scaling_factor = 2 # this is for Mac, on Windows/Linux it may vary depending on display settings
font = io.fonts.add_font_from_file_ttf("font_name.ttf", font_scaling_factor * font_size, io.fonts.get_glyph_ranges_latin())
impl.refresh_font_texture() # rasterize the large font
imgui.get_io().font_global_scale = 1 / font_scaling_factor # scale down font for display
# ...

while not glfw.window_should_close(self.window):
    # draw stuff
    imgui.push_font(font)
    # draw text
    imgui.pop_font()
```

**Comment by swistakm** [comment]
@iliyang thank you for your notes. I will have to include that in the project documentation.
