### ISSUE TITLE
Problem on installing integrations in zsh

### ISSUE THREAD

**Issue by gustavofuhr** [swistakm/pyimgui#51]
Hello,

I had a problem when running any variant of pip install integrations with zsh:
```
pip install imgui[pygame]
zsh: no matches found: imgui[pygame]
```
With good old bash is working fine. For zsh, you need to escape the brackets:

```
pip install imgui\[pygame\]
```

Was a bit tricky to find this, so I tough about sharing.

**Comment by augu5te** [comment]
This issue is not related to this project but to interaction between pip and zsh. Note you can also use quoting in place of escaping:
   `pip install "imgui[pygame]"`

**Comment by swistakm** [comment]
@gustavofuhr, @augu5te thanks you both for explaining. This is indeed a zsh thing. I'm going to close the issue. If anyone will have problem with this it can be easily found in the list of issues.
