### ISSUE TITLE
Set column width not implemented

### ISSUE THREAD

**Issue by rspencer01** [swistakm/pyimgui#52]
It seems it wasn't implemented in the version of imgui that is in this repo.  Can we update that version and implement some of the new functions?

**Comment by swistakm** [comment]
@rspencer01 of course. I will try to find some time this week to handle this.

**Comment by pconerly** [comment]
@swistakm is this something you'd label with `Help Wanted`?

**Comment by pconerly** [comment]
So just a note, `SetColumnWidth` got implemented in 1.51, and our imgui is on 1.46.

**Comment by swistakm** [comment]
@pconerly yes. Generally everything in theissue list can be taken/fixed by anyone.

I think I will rename the label to "easy to pick" because this is how I am using it most of the time :)

**Comment by swistakm** [comment]
Fixed as part of #73 by @tim-rex

**Comment by swistakm** [comment]
Released as `1.0.0`
