### ISSUE TITLE
how to use PlotLine in pyimgui?

### ISSUE THREAD

**Issue by zjqzyc** [swistakm/pyimgui#75]
Hey,
I am trying to draw a diagram in pyimgui but I cannot find any document or wiki about the function like PlotLine in C++? is it exist or not?

**Comment by swistakm** [comment]
@zjqzyc it is still missing. If I find enough time I will try to fit it into incoming 1.0.0 release.

**Comment by swistakm** [comment]
The plot_lines function was introduced in #85 and is now available in pre-release version `1.0.0a2`.

**Comment by swistakm** [comment]
Released as `1.0.0`
