### ISSUE TITLE
How to install the pre-release version?

### ISSUE THREAD

**Issue by pconerly** [swistakm/pyimgui#79]
Hey,

I'm trying to install the pre-release version here https://pypi.org/project/imgui/1.0.0a1/ to get `is_mouse_clicked`. I first uninstalled the version I had in my virtualenv, and then:

```
pip install imgui==1.0.0a1
pip install --pre imgui
pip install --pre imgui==1.0.0a1
```

Any ideas?

//edit I'm on OSX El Capitan 10.11.4. I'm looking at the files, and it looks like there's just `macosx_10_12`. When I download that macosx wheel and install I get:

```
$ pip install files/imgui-1.0.0a1-cp36-cp36m-macosx_10_12_x86_64.whl 
imgui-1.0.0a1-cp36-cp36m-macosx_10_12_x86_64.whl is not a supported wheel on this platform.
```

But when I look at https://pypi.org/project/imgui/0.1.0/#files it has the same mac version.

Could you add the source `.tar.gz` that `0.1.0` has to the pre-release? Maybe my pip installs via that?

**Comment by swistakm** [comment]
Sorry for the delay. I was swarmed with personal stuff. I will take a closer look at this asap.

**Comment by swistakm** [comment]
This should now work with version 1.0.0a2 that inlcudes builds for Python3.7. There is also sdist package for that version so it should be possible to compile it locally if there is no matching wheel for a platform.
