### ISSUE TITLE
Support Python 3.7

### ISSUE THREAD

**Issue by lenormf** [swistakm/pyimgui#81]
Looks like the newer version of Python isn't supported, which causes issues similar to what's described in #79.

Thanks!

**Comment by lenormf** [comment]
Thank you!

**Comment by traverseda** [comment]
Seems to be working fine for me?

**Comment by swistakm** [comment]
Official support for 3.7 will be released with 1.0.0 version. It will be available soon as prerelease version 1.0.0a2 with recent merged changes.

**Comment by swistakm** [comment]
The 1.0.0a2 pre-release version is now available on PyPi with both sdist and wheel packages covering Python 3.7 version

**Comment by swistakm** [comment]
Released as `1.0.0`
