### ISSUE TITLE
Automatically generate bindings?

### ISSUE THREAD

**Issue by traverseda** [swistakm/pyimgui#84]
It looks like https://github.com/cimgui/cimgui has pretty good support for automatically generating bindings. I notice that this is pretty out of date, and that imgui is adding new features pretty fast. So it would be nice if the bindings were being partially auto-generated.

What I'm running up against right now is that you can't tell it to focus on an input. I'm trying to build an interactive repl for python, and not being able to set focus means you have to select the input widget manually whenever you enter a line in the repl.

**Comment by swistakm** [comment]
It is nice idea to have all missing APIs autogenerated. Do you think that this approach could be easily implemented here?

Also do you know what particular interface is missing here to solve your problem?

**Comment by traverseda** [comment]
The interface I'm missing for the repl is `ImGui::SetKeyboardFocusHere(0);`

It sure looks like that approach would work here, I'd be trying it myself if I was more familiar with building C applications in a python package. From what I understand, cimgui provides a bunch of json-files that are autogenerated based on the original cpp files. You can see one [here](https://github.com/cimgui/cimgui/blob/master/generator/output/definitions.json). You'd generate python code based on those json files, with the presumption being that the json files would be kept up to date by the imgui team.

So you'd take something like

```json
  "igCaptureKeyboardFromApp": [
    {
      "funcname": "CaptureKeyboardFromApp",
      "args": "(bool capture)",
      "ret": "void",
      "comment": "",
      "call_args": "(capture)",
      "argsoriginal": "(bool capture=true)",
      "stname": "ImGui",
      "argsT": [
        {
          "type": "bool",
          "name": "capture"
        }
      ],
      "defaults": {
        "capture": "true"
      },
      "signature": "(bool)",
      "cimguiname": "igCaptureKeyboardFromApp"
    }
  ],
```

and automatically generate python classes from it. It's a big chunk of work, but the good thing is cimgui is maintaining that for you.

**Comment by traverseda** [comment]
Well, there'd need to be a custom solutions used to turn it into a python-friendly API. I definitely don't have enough C experience to know what I'm talking about, but the way I'd approach it is by using jinja2 to generate actual python files from those specifications, call it "imgui-lowlevel". It would generate annoying to use bindings for everything, so at least you can drop down to those bindings for things we don't have a nice wrapper for.

We'd approach fixing those bindings from two different directions.

 * Improve the code generator, automatically converting `(sometype*, length)` values to `Vector<sometype>` values, as an example.
 * Writing "mainline" wrappers that provide a nice pythonic interface to those "imgui-lowlevel" calls.

**Comment by lubieowoce** [comment]
That being said, it might be possible to heuristically convert the out/inout/pointer+length idioms to Python – imgui seems pretty consistent in their usage and has good `const` annotations on everything, so we could guess if something's used as an "out" parameter based on those. A human would have to inspect the generated wrapper functions to see if they work as intended, but it should reduce the amount of work.

**Comment by lubieowoce** [comment]
We should also look into existing bindings – someone might have already done autogenerated low-level → high-level bindings for another language, maybe it's possible to reuse that work?

**Comment by traverseda** [comment]
An example I put together very quickly. I tried to doing without any python code, just jinja2 code, and that was a mistake. Next time I'll do a data-normalization step in python first.

[example.py.txt](https://github.com/swistakm/pyimgui/files/2498290/example.py.txt)
[template_pyImgui.py.j2.txt](https://github.com/swistakm/pyimgui/files/2498291/template_pyImgui.py.j2.txt)

As you can see, there are definitely some issues. For example, some of the arguments are `values: const float*,`.

It's generating statically-typed python code so the python syntax might be a bit different from what you're used to. That's not a mistake, it's how I meant to do it.

**Comment by traverseda** [comment]
And an example of what it generates so you don't need to download the whole file.

```python
def PlotHistogram(self, 
    label: const char*,
    values: const float*,
    values_count: int,
    scale_min: float = FLT_MAX,
    graph_size: ImVec2 = ImVec2(0,0),
    scale_max: float = FLT_MAX,
    stride: int = sizeof(float),
    values_offset: int = 0,
    overlay_text: const char* = ((void *)0),) -> void:
    #
    #Raw Item Data == {'comment': '', 'cimguiname': 'igPlotHistogram', 'stname': 'ImGui', 'args': '(const char* label,const float* values,int values_count,int values_offset,const char* overlay_text,float scale_mi
n,float scale_max,ImVec2 graph_size,int stride)', 'ret': 'void', 'funcname': 'PlotHistogram', 'argsoriginal': '(const char* label,const float* values,int values_count,int values_offset=0,const char* overlay_text=
((void *)0),float scale_min=3.40282346638528859812e+38F,float scale_max=3.40282346638528859812e+38F,ImVec2 graph_size=ImVec2(0,0),int stride=sizeof(float))', 'call_args': '(label,values,values_count,values_offset
,overlay_text,scale_min,scale_max,graph_size,stride)', 'defaults': {'scale_min': 'FLT_MAX', 'graph_size': 'ImVec2(0,0)', 'scale_max': 'FLT_MAX', 'stride': 'sizeof(float)', 'values_offset': '0', 'overlay_text': '(
(void *)0)'}, 'signature': '(const char*,const float*,int,int,const char*,float,float,ImVec2,int)', 'ov_cimguiname': 'igPlotHistogramFloatPtr', 'argsT': [{'type': 'const char*', 'name': 'label'}, {'type': 'const 
float*', 'name': 'values'}, {'type': 'int', 'name': 'values_count'}, {'type': 'int', 'name': 'values_offset'}, {'type': 'const char*', 'name': 'overlay_text'}, {'type': 'float', 'name': 'scale_min'}, {'type': 'fl
oat', 'name': 'scale_max'}, {'type': 'ImVec2', 'name': 'graph_size'}, {'type': 'int', 'name': 'stride'}]}
    pass
```

**Comment by sonoro1234** [comment]
> We should also look into existing bindings – someone might have already done autogenerated high-level bindings for another language, maybe it's possible to reuse that work?

Two examples in https://github.com/cimgui/cimgui#generate-binding

**Comment by cammm** [comment]
I just recently started working on something similar, using clang to parse the imgui headers and generating pybind11 bindings. The generator code is pretty scrappy and there are a few things that still need fixing (out params and callbacks) but if I can get it completed then the API would have full coverage with consistent naming.

https://github.com/cammm/deargui

I'm not certain I'll finish this but maybe it can inspire a similar approach using cython.

**Comment by traverseda** [comment]
I'd still like to see something done with auto-generation, but my C/cython skills are still not nearly good enough. Let me know if there's anything I can do to help out.

**Comment by traverseda** [comment]
I've auto-generated bindings from cimgui, and I can call `igGetVersion()`. It was a fair bit of work for someone as inexperienced with C as me. I wouldn't know where to start with integrations, but maybe that's something this project could use?

It's written using `python-cffi`, which probably isn't very compatible with the current cython approach.

https://github.com/traverseda/cimgui-python/

**Comment by traverseda** [comment]
@swistakm Would you be at all interested in offering me some tutoring so I can get up to speed on cython faster and hopefully get these bindings generators to work with Cython? Looking into it deeper it looks like (under cpython at least) cython has lower overhead than python-cffi.

I'm imagining an hour a week on `some-skype-equivelent` or text chat would be enough to answer my most pertinent questions, and to keep me actually motivated to make progress.

**Comment by swistakm** [comment]
@traverseda: definitely, just ping me through email (address is on my GitHub profile) and we will setup something. Maybe even this weekend.

**Comment by DGriffin91** [comment]
@swistakm @traverseda Are you still working on this? I've got a script now that will generate `cimgui.pxd` and `enums.pxd`. The generated `cimgui.pxd` is almost fully compatible with `core.pyx` in master, only a few tweaks are needed (Mostly to do with defaults). I'm just using pygccxml to parse `imgui.h`. Not sure if either of you are interested, or what progress you may have already made. 

I would love to help get pyimgui closer to 100% coverage, and up to date. I have a branch that works with the new tables and docking API as well, it didn't take much to get them working.

**Comment by traverseda** [comment]
I made a pretty big bit of progress on this using cppyy, you can see that here: https://gist.github.com/56a7c50d8b5879e5f5de292538f373cf

Just clone any given imgui tag/branch into a folder, run `cmake ./ && make` and you'll end up with auto-generated imgui bindings. Of course there's no integrations, so I haven't been able to test it very much.

I'm very impressed with cppyy's automatic bindings generation, a whole lot easier than anything else I've looked at, at least for the basic case of getting it to call `imgui.ImGui.GetVersion()`. This works with the latest tag as well as the docking branch, although once again there's no integrations so it's hard to set. Literally just "git clone" the version you want into the "imgui" sub directory and let cppyy take care of all the rest.

**Comment by traverseda** [comment]
https://github.com/traverseda/imgui_cppyy_test

This *seems* to be working, although it's hard to test since I don't have any integrations. You can see the generated objects auto-creating [here](https://github.com/swistakm/pyimgui/files/4932273/debug.log). Like I say, it seems complete and basic things like setting the backend name does work as expected:

```python
io = imgui.ImGui.GetIO()
io.BackendPlatformName = "imgui_impl_test"
```

It's based off the CPP version of imgui. I've considered generating complete bindings for [mahi-gui](https://github.com/mahilab/mahi-gui) as it's closer what I'm actually looking for, but this is definitely more mature.

@swistakm Any thoughts on next steps for this? It seems like a big thing to start trying to rip out this things Cython guts and replace them with auto-generated cppyy-based bindings.

**Comment by traverseda** [comment]
[docs.txt](https://github.com/swistakm/pyimgui/files/5283080/docs.txt)

These all *seem* to work, although obviously I don't have a real back-end. The auto-generation from cpp files is working, I just don't really have the time to learn all the skills I'd need to make the actual integrations, or to try and integrate it into this code base. I can probably find a few hours a week, but I'd definitely need guidance.

@swistakm is integrating auto-generated bindings like this something you'd even be interested in?
