### ISSUE TITLE
Some direct communication channel for new developers

### ISSUE THREAD

**Issue by swistakm** [swistakm/pyimgui#86]
I've seen that there is inflow of new developers and users in the project. This is great enjoyment to me as project has been in little stasis for some time. I would like to know better who is using it and how you discovered this project. This would help to better organize the work and give this project some direction. I was thinking about either Gitter chat or Slack channel where we could introduce ourselves tell more what we expect from the project, how we use it and what kind of improvements we would like to see in the future.

@lubieowoce, @romanesko, @pconerly, @traverseda, @lenormf, @kairyu, @cammm: what do you think?

**Comment by traverseda** [comment]
I don't really get the appeal of gitter/slack. IRC has been serving me just fine for a long time, and It's a huge pain to idle a slack channel. Some 3rd-parties my business is involved in use slack, which means that I end up with 3 or 4 slack tabs open, which is a bit of a pain.

**Comment by lubieowoce** [comment]
I think it's a good idea! Any communication channel is fine by me tbh.

**Comment by lubieowoce** [comment]
Good idea! Any communications channel is fine by me.

**Comment by traverseda** [comment]
Your comments are getting through, just github is experiencing service interruptions. They're showing up in email.

**Comment by pconerly** [comment]
I used ImGUI to make a spectrogram viewer. I used [Librosa](https://librosa.github.io/) to analyze a piece of audio, and then a user could pick a starting spot and play, and the program would play through the song while showing what spot on the spectograph the song was at.

I had some issues with getting custom GL to play nice with Imgui, I had to manually reset some GL parameters after I had rendered my spectrogram image. (But I might also just be extremely spoiled by [regl](http://regl.party/)

I come from a React/Redux web development world, so I was also consciously using a redux-style "state" and "dispatch" pattern. Every component would just take `(state, dispatch)` as it's arguments.

I was going to package this as an exe but after a week of struggling with the packaging I moved onto other things. My app was able to be packaged, but I had difficulty getting local storage to work. (I had a sqlite DB and a yaml 'preferences' file that I needed to save things in.)

(I'd also vote against slack. Gitter seems like it'd be a better option.)

**Comment by swistakm** [comment]
OK, We won't use slack then. For me the best solution would be one that I could easily use on mobile because I almost don't use computer at home. Maybe it's too early for that. Let's just try keeping discussions on this issue tracker. We can always start a new thread whenever we need to.

Regarding the milestone. Let's pick 1.65 as a target for official 1.0.0 release. I'm am now trying to fix build pipeline on Windows. When it's ready we will be able to upload next prerelease version. The milestone for 1.0.0 is already created on the issue tracker. There isn't a lot of issues in it so you can create new ones or mark existing ones that you would like to see in that release.
