### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by LuminousLizard** [swistakm/pyimgui#90]
Hello,

I have seen that on the TODO list "more examples" is noted. I'm currently learning Pyimgui and writing my own executable examples. I would add these to your project, but I wanted to ask if you want to have several small examples containing different things, OR a "fully translated" version of the ImGui demo into Python/Pyimgui ?

**Comment by LuminousLizard** [comment]
I'll rewrite the ImGui demo window into Python/Pyimgui (as much as possible so far) and add it to the examples.

**Comment by swistakm** [comment]
Sorry for the delay. We can of course rewrite the whole demo window but IMO the best would be small examples that show basic concepts of Imgui like how to handle widget changes an state. Useful would be also some examples that show how to effectively use flags or the examples that show some pitfalls like reusing same ids for different widgets.

**Comment by LuminousLizard** [comment]
OK will be done. I've already noticed the trap with "multiple use same ID" ^^.
