### ISSUE TITLE
Right arrow doesn't work on Mac in input boxes

### ISSUE THREAD

**Issue by Glench** [swistakm/pyimgui#96]
In any input box I've tried the right arrow doesn't change the cursor position, the input is ignored.

I've tried on every example/graphics backend in the docs/examples folder.

The left arrow works fine.

I'm on MacOS Sierra 10.12.6 with the following python stuff:
```
$ python --version

Python 3.7.2

$ pip freeze

cocos2d==0.6.5
Cython==0.28.2
future==0.17.1
glfw==1.7.1
imgui==0.1.0
pygame==1.9.4
pyglet==1.3.2
PyOpenGL==3.1.0
PySDL2==0.9.6
six==1.12.0
```

Any ideas for what might be going on?

**Comment by swistakm** [comment]
This should be fixed already in 1.0.0a1 / 1.0.0a2 version. This is unfortunately still a prerelease version but should be pretty stable. You’ll find information on how to install prerelease version on the [release page](https://github.com/swistakm/pyimgui/releases/tag/1.0.0a2)

**Comment by Glench** [comment]
Hm, I tried testing by downloading the alpha release and running the pygame example but I get this exception:

```
  File "pygame-example.py", line 19, in main
    io = imgui.get_io()
  File "imgui/core.pyx", line 1263, in imgui.core.get_io
  File "imgui/core.pyx", line 976, in imgui.core._IO.__init__
imgui.core.ImGuiError: ImGui assertion error (GImGui != NULL && "No current context. Did you call ImGui::CreateContext() or ImGui::SetCurrentContext()?") at imgui-cpp/imgui.cpp:2833
```

Should I make a new issue for this?

I also tried using my own script and it doesn't raise an exception but just displays a white pygame screen without any of the imgui calls.

**Comment by swistakm** [comment]
Sorry @Glench, I was on a very long vacation so couldn't answer sooner.

Yes, it is definitely a new problem and deserves a new issue. Also, is your `pygame-example.py` exactly the same as `pygame_.py` in `doc/examples` dir of this repo? I think I know where the problem might be but need to check this with exactly the same code.

**Comment by Glench** [comment]
No worries! Yes, it was an exact copy of pygame_.py in the examples directory.

**Comment by swistakm** [comment]
I assume the initial problem is resolved in latest prerelease version and the second issue is #104. I will close this and proceed to #104. Feel free to reopen if you still have issues with right arrows.
