### ISSUE TITLE
Mac tap-to-click doesn't work with glfw backend

### ISSUE THREAD

**Issue by cellularmitosis** [swistakm/pyimgui#98]
Hello,

First, thanks so much for working on pyimgui!

I installed pyimgui (`pip install imgui[full]`) and tried out the examples in `doc/examples`.

I noticed that with `doc/examples/glfw3.py`, the Mac trackpad's "tap to click" feature seems to be unreliable.  I tried 20 taps (about 1 tap per second) and six of them made it through (14 were ignored).

I don't think this is a bug in pyimgui, because:
- All of the other backends appear to work correctly
- It appears this is also an issue for nuklear: https://github.com/vurtun/nuklear/issues/407

I would doubt there's anything which can be done within the scope of this project, but I wanted to file (and close) and issue just to get it documented (and googleable).

**Comment by swistakm** [comment]
Great, thanks for the report. If it happens with only one backend it may be then issue with glfw3. Hope someday I will have more time to dig deeper into it.

**Comment by jan-matthis** [comment]
Setting
```python
glfw.set_input_mode(window, glfw.STICKY_MOUSE_BUTTONS, gl.GL_TRUE)
```
seems to make tap-to-click work fine on macOS so far.
